### ISSUE TITLE
请问大家都能访问项目地址么

### ISSUE THREAD

**Issue by StarTaleLife** [wjq990112/holiday-avatar#1]
我怎么一直访问不了

**Comment by wjq990112** [comment]
地址我引用的是 React 组件库作者做的那个 Demo，现在原作者已经换了 Demo 的地址了，如果需要看的话可以 clone 下来项目然后运行 `npm run dev` 就能看到了

**Comment by StarTaleLife** [comment]
> 地址我引用的是 React 组件库作者做的那个 Demo，现在原作者已经换了 Demo 的地址了，如果需要看的话可以 clone 下来项目然后运行 `npm run dev` 就能看到了

ok tks
